version: "3.0"

services:
  postgres:
    container_name: postgres_song_service_microservices_course
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: song
    ports:
      - '5433:5432'
