apiVersion: apps/v1
kind: Deployment
metadata:
  name: song
  namespace: k8s-program
  labels:
    app: song
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song
  template:
    metadata:
      name: song
      labels:
        app: song
    spec:
      containers:
        - name: song
          image: song:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://song-postgres:5432/song
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
      restartPolicy: Always
