apiVersion: v1
kind: Service
metadata:
  name: song
  namespace: k8s-program
spec:
  selector:
    app: song
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort