apiVersion: v1
kind: ConfigMap
metadata:
  name: song-postgres-config
  namespace: k8s-program
data:
  DB_URL: song-postgres-service
  01_init_db.sql: |
    -- Check if the database exists before creating it
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'song') THEN
      CREATE DATABASE song;
    END IF;
    END $$;

  02_create_table_song_metadata.sql: |
    CREATE TABLE song_record_metadata (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    artist VARCHAR(255),
    album VARCHAR(255),
    length VARCHAR(50),
    resource_id VARCHAR(255),
    year VARCHAR(10)
    );

