apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-song-volume
  namespace: k8s-program
  labels:
    type: local
    app: song-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-song-volume-claim
  namespace: k8s-program
  labels:
    app: song-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
